globals
    // Generated
trigger gg_trg_______u= null


//JASSHelper struct globals:

endglobals

globals
    // 抽卡相关全局变量
    private trigger gg_trg_Gacha = null
    private hashtable gachaTable = InitHashtable()
    private integer publicCardPoolKey = 0
    private integer privateCardPoolKeyBase = 1000
    private integer[] gachaCount = array
    private integer[] ssrGuarantee = array
    private integer[] urGuarantee = array
endglobals

// 卡牌等级定义
constant integer R = 0
constant integer SR = 1
constant integer SSR = 2
constant integer UR = 3
constant integer UR_PLUS = 4

// 初始化卡池
function InitGachaPool takes nothing returns nothing
    // 初始化公共卡池
    local integer i
    // 这里可以添加公共卡，示例添加一些卡
    for i = 0 to 100 do
        call SaveInteger(gachaTable, publicCardPoolKey, i, R)
    endfor
endfunction

// 获取随机卡牌等级
function GetRandomCardRank takes nothing returns integer
    local real rand = GetRandomReal(0, 100)
    if rand < 70 then
        return R
    elseif rand < 90 then
        return SR
    elseif rand < 96 then
        return SSR
    elseif rand < 99 then
        return UR
    else
        return UR_PLUS
    endif
endfunction

// 检查并触发保底机制
function CheckGuarantee takes player p returns integer
    local integer playerId = GetPlayerId(p)
    set gachaCount[playerId] = gachaCount[playerId] + 1
    if gachaCount[playerId] % 3 == 0 then
        set ssrGuarantee[playerId] = ssrGuarantee[playerId] + 1
        if ssrGuarantee[playerId] >= 3 then
            set ssrGuarantee[playerId] = 0
            return SSR
        endif
    endif
    if gachaCount[playerId] % 8 == 0 then
        set urGuarantee[playerId] = urGuarantee[playerId] + 1
        if urGuarantee[playerId] >= 1 then
            set urGuarantee[playerId] = 0
            return UR
        endif
    endif
    return -1
endfunction

// 抽取卡牌
function DrawCard takes player p returns integer
    local integer guaranteedRank = CheckGuarantee(p)
    if guaranteedRank != -1 then
        return guaranteedRank
    endif
    return GetRandomCardRank()
endfunction

// F4按键触发抽卡
function GachaActions takes nothing returns nothing
    local player p = GetTriggerPlayer()
    local integer i
    local integer cardRank
    
    for i = 0 to 2 do
        set cardRank = DrawCard(p)
        // 这里可以添加卡牌展示逻辑
        call DisplayTextToPlayer(p, 0, 0, "抽到卡牌等级: " + I2S(cardRank))
    endfor
endfunction

// 初始化抽卡触发器
function InitTrig_Gacha takes nothing returns nothing
    set gg_trg_Gacha = CreateTrigger()
    call TriggerRegisterPlayerKeyEvent(gg_trg_Gacha, Player(0), OSKEY_F4, KEY_STATE_PRESSED, 0)
    call TriggerAddAction(gg_trg_Gacha, function GachaActions)
endfunction


//===========================================================================
// 
// 只是另外一张魔兽争霸的地图
// 
//   Warcraft III map script
//   Generated by the Warcraft III World Editor
//   Date: Thu May 08 15:26:59 2025
//   Map Author: 未知
// 
//===========================================================================
//***************************************************************************
//*
//*  Global Variables
//*
//***************************************************************************
function InitGlobals takes nothing returns nothing
endfunction
//***************************************************************************
//*
//*  Unit Creation
//*
//***************************************************************************
//===========================================================================
function CreateUnitsForPlayer0 takes nothing returns nothing
    local player p= Player(0)
    local unit u
    local integer unitID
    local trigger t
    local real life
    set u=CreateUnit(p, 'h000', 262.4, 299.7, 170.458)
    set u=CreateUnit(p, 'h000', 33.1, 161.5, 246.343)
    set u=CreateUnit(p, 'h002', 443.1, 33.7, 0.000)
    set u=CreateUnit(p, 'h001', 136.7, 9.0, 184.038)
    set u=CreateUnit(p, 'h001', 631.8, 327.1, 196.079)
    set u=CreateUnit(p, 'h003', 851.9, 216.7, 353.946)
    set u=CreateUnit(p, 'h002', 628.7, - 162.0, 61.448)
    set u=CreateUnit(p, 'h004', - 684.2, 203.2, 240.960)
    set u=CreateUnit(p, 'h005', - 415.6, 401.6, 202.242)
    set u=CreateUnit(p, 'h007', - 114.0, 168.2, 59.987)
    set u=CreateUnit(p, 'h006', - 347.2, 21.3, 359.692)
    set u=CreateUnit(p, 'h006', 255.9, - 405.9, 163.185)
endfunction
//===========================================================================
function CreatePlayerBuildings takes nothing returns nothing
endfunction
//===========================================================================
function CreatePlayerUnits takes nothing returns nothing
    call CreateUnitsForPlayer0()
endfunction
//===========================================================================
function CreateAllUnits takes nothing returns nothing
    call CreatePlayerBuildings()
    call CreateUnitsForPlayer0() // INLINED!!
endfunction
//***************************************************************************
//*
//*  Triggers
//*
//***************************************************************************
//===========================================================================
// Trigger: 简介
//===========================================================================
function Trig_______uActions takes nothing returns nothing
    // YDWE是《魔兽争霸III》地图编辑器的一个增强Mod。
    // 　　你可以从www.ydwe.net获取最新的YDWE。
    // 　　你可以由YDWE附带的演示地图开始，快速了解YDWE的功能。
    // 　　当你的地图意外损坏时，你可以在backups目录找到你最近26次保存的地图。
    // 　　当你的YDWE不能正常工作时，你可以前往www.ydwe.net联系我们。
endfunction
//===========================================================================
function InitTrig_______u takes nothing returns nothing
    set gg_trg_______u=CreateTrigger()
    call TriggerAddAction(gg_trg_______u, function Trig_______uActions)
endfunction
//===========================================================================
function InitCustomTriggers takes nothing returns nothing
    call InitTrig_______u()
endfunction
//***************************************************************************
//*
//*  Players
//*
//***************************************************************************
function InitCustomPlayerSlots takes nothing returns nothing
    // Player 0
    call SetPlayerStartLocation(Player(0), 0)
    call SetPlayerColor(Player(0), ConvertPlayerColor(0))
    call SetPlayerRacePreference(Player(0), RACE_PREF_HUMAN)
    call SetPlayerRaceSelectable(Player(0), true)
    call SetPlayerController(Player(0), MAP_CONTROL_USER)
endfunction
function InitCustomTeams takes nothing returns nothing
    // Force: TRIGSTR_002
    call SetPlayerTeam(Player(0), 0)
endfunction
//***************************************************************************
//*
//*  Main Initialization
//*
//***************************************************************************
//===========================================================================
function main takes nothing returns nothing
    call SetCameraBounds(- 3328.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), - 3584.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM), 3328.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), 3072.0 - GetCameraMargin(CAMERA_MARGIN_TOP), - 3328.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), 3072.0 - GetCameraMargin(CAMERA_MARGIN_TOP), 3328.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), - 3584.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM))
    call SetDayNightModels("Environment\\DNC\\DNCLordaeron\\DNCLordaeronTerrain\\DNCLordaeronTerrain.mdl", "Environment\\DNC\\DNCLordaeron\\DNCLordaeronUnit\\DNCLordaeronUnit.mdl")
    call NewSoundEnvironment("Default")
    call SetAmbientDaySound("LordaeronSummerDay")
    call SetAmbientNightSound("LordaeronSummerNight")
    call SetMapMusic("Music", true, 0)
    call CreateAllUnits()
    call InitBlizzard()


    call InitGlobals()
    call InitTrig_______u() // INLINED!!
    call InitGachaPool()
    call InitTrig_Gacha()
endfunction
//***************************************************************************
//*
//*  Map Configuration
//*
//***************************************************************************
function config takes nothing returns nothing
    call SetMapName("只是另外一张魔兽争霸的地图")
    call SetMapDescription("没有说明")
    call SetPlayers(1)
    call SetTeams(1)
    call SetGamePlacement(MAP_PLACEMENT_USE_MAP_SETTINGS)
    call DefineStartLocation(0, - 2112.0, 1856.0)
    // Player setup
    call InitCustomPlayerSlots()
    call SetPlayerSlotAvailable(Player(0), MAP_CONTROL_USER)
    call InitGenericPlayerSlots()
endfunction




//Struct method generated initializers/callers:

